
package ua.com.cs.model.ifobswm;

import javax.jws.*;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WMServiceBean", targetNamespace = "http://wm.webservices.ifobs.cs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WMServiceBean {


    /**
     * 
     * @param sWebServiceXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "callService", targetNamespace = "http://wm.webservices.ifobs.cs.com/", className = "ua.com.cs.model.ifobswm.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://ift.webservices.ifobs.cs.com/", className = "ua.com.cs.model.ifobswm.CallServiceResponse")
    @Action(input = "http://wm.webservices.ifobs.cs.com/WMServiceBean/callServiceRequest", output = "http://ift.webservices.ifobs.cs.com/WMServiceBean/callServiceResponse")
    public String callService(
        @WebParam(name = "sWebServiceXML", targetNamespace = "")
        String sWebServiceXML);

}
